Repository Yicong-Huang/Wildfires, pull requests merged in 2019-09, with the labels that each got.

#89 Environment & Service: change the hard-coded url
  frontend/src/app/services/fire-service/fire.service.ts
  frontend/src/app/services/map-service/map.service.ts
  frontend/src/app/services/search/search.service.ts
  frontend/src/environments/environment.ts
Labels: feature

#97 fix: invalid default batch_num in tweet crawler
  backend/task/text_from_twitter_runnable.py
Labels: fixed

#88 annotation: USGS and NOAA
  backend/data_preparation/crawler/noaa_crawler.py
  backend/data_preparation/crawler/usgs_crawler.py
  backend/data_preparation/dumper/noaa_dumper.py
Labels: documentation

#70 WebApp: Docstring and annotations
  backend/web/__init__.py
  backend/web/router/data_router.py
  backend/web/router/dropDownMenu_router.py
  backend/web/router/root_router.py
  backend/web/router/search_router.py
  backend/web/router/tweet_router.py
  sql/autocomplete.sql
  sql/boundaries_cities.sql
  sql/boundaries_counties.sql
  sql/boundaries_states.sql
  sql/point_aggr_tweet.sql
Labels: documentation
